name: notes
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flex_color_scheme: ^7.3.1
  package_info_plus: ^5.0.1 
  colornames: 
  flutter_native_splash: ^2.3.10 
  path_provider: ^2.1.2  
  uuid: ^4.3.3  
  hive_flutter: ^1.1.0  
  json_annotation: ^4.8.1 
  freezed_annotation: ^2.4.1  
  build_runner: ^2.4.8 
  json_serializable: ^6.7.1 
  freezed: ^2.4.7  
  rebloc: ^0.4.0
  flutter_redux: ^0.10.0
  redux: ^5.0.0
  get: ^4.6.6
flutter:
  uses-material-design: true
