name: notes
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flex_color_scheme: ^7.3.1
  colornames:
  flutter_native_splash: ^2.3.10
  path_provider: ^2.1.2
  build_runner: ^2.4.8
  states_rebuilder: ^6.4.0
  manager:
    path: D://adn//apps//manager
  objectbox: ^1.7.0
  objectbox_flutter_libs: any
  objectbox_generator: any
dev_dependencies:
  flutter_launcher_icons: "^0.14.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/vision.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/vision.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/vision.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/vision.png"
flutter:
  uses-material-design: true
# dart run flutter_native_splash:create --path=splash.yaml
# dart run flutter_launcher_icons
