name: notes
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  states_rebuilder: 6.3.0
  hive_flutter:
  flex_color_scheme:
  uuid: ^4.2.1
  colornames: ^0.1.0
  path_provider: ^2.1.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  appwrite: ^11.0.1
  fluent_ui: ^4.8.6
  manager:
    git: https://github.com/kmcite2020/manager
dev_dependencies:
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.4.6
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/app_icon.png"
flutter:
  uses-material-design: true
# dart run flutter_launcher_icons